### ISSUE TITLE
Help: How do I run locally?

### ISSUE THREAD

**Issue by rmharrison** [byexamples/byexample#59] opened 2018-10-20 04:40 UTC
```
$ pip install --user byexample 
```
Installed the module (verified with `pip show byexample`), but 

```
$ byexample
byexample: command not found
```

So I tried git cloning and running locally...
```
$ make deps
$ python byexample/byexample.py
Traceback (most recent call last):
  File "byexample/byexample.py", line 1, in <module>
    from .cache import RegexCache, cache_filepath
ValueError: Attempted relative import in non-package
```

I also tried python3
```
$ python3 byexample/byexample.py
Traceback (most recent call last):
  File "byexample/byexample.py", line 1, in <module>
    from .cache import RegexCache, cache_filepath
ModuleNotFoundError: No module named '__main__.cache'; '__main__' is not a package
```

Versions...
```
$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
$ python --version
Python 2.7.14
$ python3 --version
Python 3.6.3
$ lsb_release -a
Description:	Ubuntu 17.10
```

**How do I run the package?**

The only way I've found to run the program is via `test/r.py`, but that doesn't seem right.

**Comment by eldipa** [comment] 2018-10-20 14:05
From the first error, I guess that there is an issue in your ``$PATH``. Could you print it?

This is what I get from my debian:

```shell
$ echo $PATH
/usr/local/bin:/usr/bin:<...>:/home/user/.local/bin:<...>
```

When I installed ``byexample`` using ``pip install --user``, the executable was installed in ``/home/user/.local/bin``, that's why it works at least on my machine.

If you run ``pip show`` it will print the location of the libray, I used that path *as a hint* to know where was the executable:

```shell
$ pip show byexample
Name: byexample
Version: 7.4.1
<...>
Location: /home/user/.local/lib/python2.7/site-packages
```

So, the libs are in ``/home/user/.local/lib/python2.7/site-packages`` therefor the executable should be in ``/home/user/.local/bin``. What does it say on your machine?

There are several possible solutions:
 - if the problem is in the ``$PATH``, you can extend it (in my case I would do ``export PATH=$PATH:/home/user/.local/bin`` to add that folder to my ``$PATH``)
 - install ``byexample`` in the system directly (``sudo pip install byexample``)
 - or you can instal it inside a ``virtualenv``

Nevertheless, I would like to know what is the cause of this problem, I would like to put some notes in the installation section. 

##### Extra comments:

Running ``python byexample/byexample.py`` it will not work as you see because it is intended to be installed and executed as a program and not as a python file (that's the reason why then it cannot find the rest of the modules)

And ``test/r.py``, as you deducted is not intended to be run in "production" (it is a hacked script to enable coverage metrics)

**Comment by eldipa** [comment] 2018-10-26 12:10
I removed the ``--user`` from the documentation, it should be more clear now.

I'm going to close this ticket. If the problem persists, feel free to reopen it.

Thanks for the help!

**Closed by eldipa** 2018-10-26 12:10 UTC
